export type MemoryType = 
  | 'Short Term Memory' 
  | 'Long Term Memory' 
  | 'Conversation Memory' 
  | 'Preference Memory' 
  | 'Routine Memory' 
  | 'Family Habit Memory' 
  | 'Goal Memory';

export type RecommendationCategory = 
  | 'Health' 
  | 'Finance' 
  | 'Meal' 
  | 'Shopping' 
  | 'Education' 
  | 'Travel' 
  | 'Relationship' 
  | 'Parenting' 
  | 'Smart Home' 
  | 'Insurance';

export type NotificationPriority = 'Critical' | 'Important' | 'Information' | 'Suggestion';

export type PrivacyLevel = 'Private' | 'Family' | 'Parent Only' | 'Admin';

export interface AIMemory {
  id: string;
  type: MemoryType;
  title: string;
  content: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  privacyLevel: PrivacyLevel;
  relatedMemberId?: string;
  confidenceScore?: number;
}

export interface AIContextModuleState {
  moduleName: string;
  summary: string;
  itemCount: number;
  lastUpdated: string;
  keyInsights: string[];
  status: 'optimal' | 'attention_needed' | 'action_required';
}

export interface AIContext {
  id: string;
  timestamp: string;
  familyId: string;
  moodContext: AIContextModuleState;
  calendarContext: AIContextModuleState;
  shoppingContext: AIContextModuleState;
  inventoryContext: AIContextModuleState;
  healthContext: AIContextModuleState;
  financeContext: AIContextModuleState;
  insuranceContext: AIContextModuleState;
  mealPlannerContext: AIContextModuleState;
  travelContext: AIContextModuleState;
  educationContext: AIContextModuleState;
  parentingContext: AIContextModuleState;
  memoriesContext: AIContextModuleState;
  smartHomeContext: AIContextModuleState;
  tasksContext: AIContextModuleState;
  achievementContext: AIContextModuleState;
  notificationContext: AIContextModuleState;
  overallWellnessScore: number;
}

export interface AIRecommendation {
  id: string;
  category: RecommendationCategory;
  title: string;
  description: string;
  actionableSteps: string[];
  impactLevel: 'Tinggi' | 'Sedang' | 'Rendah';
  suggestedBy: 'AI Core' | 'Gemini Engine';
  createdAt: string;
  isApplied: boolean;
  relatedModule?: string;
}

export interface AIInsight {
  id: string;
  title: string;
  category: RecommendationCategory;
  type: 'trend' | 'anomaly' | 'positive_pattern' | 'risk_warning';
  description: string;
  dataMetric: string;
  recommendation: string;
  date: string;
}

export type AutomationTrigger = 
  | 'Tanggal' 
  | 'Jam' 
  | 'Event' 
  | 'Mood' 
  | 'Inventory' 
  | 'Budget' 
  | 'Health' 
  | 'Calendar' 
  | 'Location';

export type AutomationAction = 
  | 'Create Reminder' 
  | 'Create Task' 
  | 'Send Notification' 
  | 'Suggest Meal' 
  | 'Suggest Shopping' 
  | 'Generate Report' 
  | 'Run Workflow';

export interface AIAutomation {
  id: string;
  title: string;
  trigger: AutomationTrigger;
  triggerCondition: string;
  action: AutomationAction;
  actionPayload: string;
  isActive: boolean;
  lastExecuted?: string;
  executionCount: number;
  privacyLevel: PrivacyLevel;
}

export type WorkflowNodeType = 'Trigger' | 'Condition' | 'Action' | 'Delay' | 'Loop';

export interface WorkflowNode {
  id: string;
  type: WorkflowNodeType;
  title: string;
  config: Record<string, any>;
  position: { x: number; y: number };
}

export interface WorkflowConnection {
  id: string;
  fromNodeId: string;
  toNodeId: string;
  label?: string;
}

export interface AIWorkflow {
  id: string;
  title: string;
  description: string;
  nodes: WorkflowNode[];
  connections: WorkflowConnection[];
  isActive: boolean;
  createdAt: string;
}

export interface AITask {
  id: string;
  title: string;
  category: string;
  assignedMemberName: string;
  priority: 'Tinggi' | 'Sedang' | 'Biasa';
  status: 'Pending' | 'In Progress' | 'Completed';
  dueDate: string;
  autoGeneratedByAI: boolean;
  notes?: string;
}

export interface AIGoal {
  id: string;
  title: string;
  category: 'Kesehatan' | 'Keuangan' | 'Pendidikan' | 'Relationship' | 'Travel' | 'Habit';
  targetValue: number;
  currentValue: number;
  unit: string;
  targetDate: string;
  assignedMemberId?: string;
  status: 'On Track' | 'At Risk' | 'Achieved';
}

export interface AIHabit {
  id: string;
  habitName: string;
  memberId: string;
  memberName: string;
  streakCount: number;
  frequency: 'Harian' | 'Mingguan';
  aiScore: number;
  lastCompletedDate?: string;
}

export interface AIBriefing {
  id: string;
  date: string;
  greetingText: string;
  bulletBriefings: string[];
  decisionSupportNotes: { topic: string; recommendation: string; status: 'Aman' | 'Perhatian' | 'Kritis' }[];
  wellnessScore: number;
  aiConfidenceScore: number;
}

export interface AIChatMessage {
  id: string;
  sender: 'user' | 'ai';
  senderName?: string;
  text: string;
  timestamp: string;
  category?: string;
  attachments?: { type: 'voice' | 'image' | 'pdf' | 'document'; name: string; url?: string }[];
}

export interface AIChatSession {
  id: string;
  title: string;
  messages: AIChatMessage[];
  lastUpdated: string;
  tokenCount: number;
}

export interface AISearchResult {
  id: string;
  module: string;
  title: string;
  subtitle: string;
  date: string;
  snippet: string;
  deepLinkTab: string;
}

export interface AIReport {
  id: string;
  reportType: 'Weekly Summary' | 'Monthly Summary' | 'Family Summary' | 'Health Summary' | 'Finance Summary' | 'Education Summary';
  generatedDate: string;
  periodText: string;
  keyHighlights: string[];
  dataMetrics: Record<string, any>;
  downloadUrl?: string;
}

export interface AINotification {
  id: string;
  title: string;
  message: string;
  priority: NotificationPriority;
  timestamp: string;
  isRead: boolean;
  moduleLink?: string;
}
